name: pylintBadge

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: src
          python-version: 3.11
